// ─── MISSION PLANNER — deterministic recommendations ────────────────────────
// "What is your mission?" → weights → normalised scoring in shared/recommend.js.
// Every pick shows the numbers behind it. No LLM in the loop.

import { useMemo, useState } from 'react';
import { useMobile } from '../hooks/useTheme.js';
import { MONO, SF, EASE, GlobalMotion, Skeleton, ComparisonBar } from '../components/design.jsx';
import { LabLogo } from '../components/LabLogo.jsx';
import { ORG_CONFIG } from '../models-data.js';
import { useLLMs, useMedia, useSpeech } from '../data/useDomain.js';
import { PageFrame, PageTitle, DataStatus, Panel, Label, Chip, Btn, EmptyState, BadgeTag, SourceTag, GREEN, GOLD, BLUE, PURPLE, RED } from '../components/ui.jsx';
import { MISSIONS, DEFAULT_WEIGHTS, recommend } from '../../shared/recommend.js';
import { fmtMetric, isNum, NA, metric } from '../../shared/metrics.js';
import { AddToBattle } from '../domains/comparison/BattleControls.jsx';

const SLIDERS = [
  { key: 'quality', label: 'Quality', color: GREEN, hint: 'ELO / index of the mission' },
  { key: 'speed',   label: 'Speed',   color: PURPLE, hint: 'tokens/s, latency or generation time' },
  { key: 'cost',    label: 'Cost',    color: GOLD, hint: 'lower price scores higher (log scale)' },
  { key: 'context', label: 'Context', color: BLUE, hint: 'context window (LLM missions)' },
  { key: 'open',    label: 'Open weights', color: GREEN, hint: 'bonus for downloadable weights' },
];

function llmCandidates(models) {
  return models.filter(m => m.inArena || isNum(m.aa?.intelligence)).map(m => ({ id: m.id, name: m.name, org: m.org, slug: m.slug, isReasoning: m.isThinking, kind: 'llm', metrics: {
    elo: m.arena?.elo, intelligence: m.aa?.intelligence, codingIndex: m.aa?.codingIndex, agenticIndex: m.aa?.agenticIndex,
    priceBlended: m.priceBlended, priceIn: m.priceIn, speed: m.aa?.speed, ttft: m.aa?.ttft, context: m.context, open: m.isOpen,
  } }));
}
function mediaCandidates(rows, kind) {
  return rows.map(r => ({ id: r.id, name: r.name, org: r.org, kind, board: r.board, metrics: { elo: r.elo, pricePerImage: r.pricePerImage, pricePerSecond: r.pricePerSecond, genTime: r.genTime, open: r.isOpen } }));
}

export default function MissionPlannerPage({ onNavigate, slug }) {
  const mobile = useMobile();
  const llms = useLLMs(); const media = useMedia(); const speech = useSpeech();
  const [missionId, setMissionId] = useState(MISSIONS.some(m => m.id === slug) ? slug : 'chat');
  const [weights, setWeights] = useState({ ...DEFAULT_WEIGHTS });
  const [touched, setTouched] = useState(false);
  const mission = MISSIONS.find(m => m.id === missionId);

  const rows = useMemo(() => {
    switch (mission.pool) {
      case 'llm': return llmCandidates(llms.models);
      case 'image': return mediaCandidates(media.boards?.['text-to-image'] ?? [], 'image');
      case 'image-edit': return mediaCandidates(media.boards?.['image-edit'] ?? [], 'image');
      case 'video': return mediaCandidates(media.boards?.['text-to-video'] ?? [], 'video');
      case 'tts': return speech.tts.map(r => ({ id: r.modelId ?? r.id, name: r.name, org: r.org, kind: 'tts', metrics: { ttsQuality: r.elo, pricePer1mChars: r.pricePer1mChars, ttft: r.ttft, open: r.isOpen } }));
      case 'stt': return speech.stt.map(r => ({ id: r.id, name: r.name, org: r.org, kind: 'stt', metrics: { wer: r.wer, rtfx: r.rtfx, pricePerMinute: null, open: r.isOpen } }));
      default: return [];
    }
  }, [mission, llms.models, media.boards, speech.tts, speech.stt]);

  const effective = touched ? weights : { ...DEFAULT_WEIGHTS, ...(mission.preset ?? {}) };
  const result = useMemo(() => rows.length ? recommend(mission, rows, effective) : null, [mission, rows, effective]);
  const loading = (mission.pool === 'llm' && llms.loading && !llms.models.length) || (mission.pool.startsWith('image') || mission.pool === 'video' ? media.loading && !Object.keys(media.boards).length : false) || (mission.pool === 'stt' && speech.loading && !speech.stt.length);

  const set = (k, v) => { setTouched(true); setWeights(w => ({ ...w, [k]: v })); };
  const pickMission = id => { setMissionId(id); setTouched(false); setWeights({ ...DEFAULT_WEIGHTS }); };

  return (
    <PageFrame mobile={mobile}>
      <GlobalMotion />
      <PageTitle mobile={mobile} eyebrow="Mission Planner" title="What is your mission?" subtitle="Pick the job, weight what matters, and get a shortlist computed from the live data — with the arithmetic shown. Nothing here is generated by a language model."
        status={<DataStatus status={llms.status} fetchedAt={llms.data?.fetchedAt} sources={['arena', 'openrouter', 'openasr', ...(llms.capabilities?.aa ? ['aa'] : [])]} loading={llms.loading} />} />

      {/* Mission */}
      <Panel style={{ marginBottom: 12 }} title="Mission">
        <div style={{ display: 'flex', gap: 6, flexWrap: 'wrap' }}>
          {MISSIONS.map(m => <Chip key={m.id} active={missionId === m.id} label={m.label} onClick={() => pickMission(m.id)} />)}
        </div>
        <p style={{ fontSize: 12.5, color: 'var(--muted)', margin: '10px 0 0', lineHeight: 1.5 }}>
          {mission.desc} Quality metric: <span style={{ fontFamily: MONO, color: 'var(--text)' }}>{metric(mission.quality).label}</span> · cost: <span style={{ fontFamily: MONO, color: 'var(--text)' }}>{metric(mission.cost).label}</span> · speed: <span style={{ fontFamily: MONO, color: 'var(--text)' }}>{metric(mission.speed).label}</span>.
        </p>
      </Panel>

      {/* Priorities */}
      <Panel style={{ marginBottom: 16 }} title="Priorities" action={touched && <Btn small onClick={() => { setTouched(false); setWeights({ ...DEFAULT_WEIGHTS }); }}>Reset to mission default</Btn>}>
        <div style={{ display: 'grid', gridTemplateColumns: mobile ? '1fr' : 'repeat(5, 1fr)', gap: mobile ? 10 : 16 }}>
          {SLIDERS.map(s => (
            <label key={s.key} style={{ display: 'flex', flexDirection: 'column', gap: 6 }}>
              <span style={{ display: 'flex', justifyContent: 'space-between' }}><Label color={s.color}>{s.label}</Label><span style={{ fontFamily: MONO, fontSize: 11, color: 'var(--text)' }}>{Math.round(effective[s.key] * 100)}%</span></span>
              <input type="range" min="0" max="100" value={Math.round(effective[s.key] * 100)} onChange={e => set(s.key, +e.target.value / 100)} style={{ width: '100%', accentColor: s.color }} />
              <span style={{ fontSize: 10.5, color: 'var(--muted2)' }}>{s.hint}</span>
            </label>
          ))}
        </div>
      </Panel>

      {loading ? <Skeleton height={360} /> : !result || !result.scored.length ? (
        <EmptyState title="Not enough data for this mission" body={result?.reason ?? `No candidates carry a ${metric(mission.quality).label} value from a configured source.`} />
      ) : (
        <>
          <div style={{ display: 'grid', gridTemplateColumns: mobile ? '1fr' : 'repeat(4, 1fr)', gap: 10, marginBottom: 16 }}>
            {[['primary', 'Primary pick', GREEN], ['bestValue', 'Best value', GOLD], ['budget', 'Budget pick', BLUE], ['fastest', 'Fastest pick', PURPLE]].map(([k, label, color], i) => {
              const p = result.picks[k];
              return (
                <div key={k} style={{ background: 'var(--card)', border: '0.5px solid var(--sep)', borderTop: `2px solid ${color}`, padding: 14, minWidth: 0, display: 'flex', flexDirection: 'column', gap: 6, animation: `aiwar-fade-up 500ms ${EASE} ${i * 70}ms both` }}>
                  <Label color={color}>{label}</Label>
                  {p ? (
                    <>
                      <div style={{ display: 'flex', alignItems: 'center', gap: 8, minWidth: 0 }}><LabLogo org={p.org} size={14} /><span style={{ fontSize: 15, fontWeight: 700, color: 'var(--text)', letterSpacing: '-0.03em', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{p.name}</span></div>
                      <div style={{ fontSize: 10.5, color: 'var(--muted)' }}>{p.org} · score {(p.score * 100).toFixed(0)}/100</div>
                      <ul style={{ margin: '4px 0 0', paddingLeft: 14, fontSize: 11.5, color: 'var(--muted)', lineHeight: 1.5 }}>{p.why.map((w, j) => <li key={j}>{w}</li>)}</ul>
                      <div style={{ marginTop: 'auto', paddingTop: 6, display: 'flex', gap: 6, flexWrap: 'wrap' }}>
                        {p.slug && <Btn small onClick={() => onNavigate({ type: 'model', slug: p.slug })}>Profile</Btn>}
                        <AddToBattle item={{ id: p.id, kind: p.kind, name: p.name, org: p.org, board: p.board }} />
                      </div>
                    </>
                  ) : (
                    <div style={{ fontSize: 12, color: 'var(--muted)', lineHeight: 1.5 }}><span style={{ fontFamily: MONO, color: 'var(--muted2)' }}>{NA}</span> · {k === 'fastest' ? (result.missing.speed ?? 'no speed data') : k === 'budget' || k === 'bestValue' ? (result.missing.cost ?? 'no cost data') : 'no candidates'}</div>
                  )}
                </div>
              );
            })}
          </div>

          <Panel title={`Ranked shortlist · ${result.scored.length} candidates`} action={<span style={{ fontFamily: MONO, fontSize: 10, color: 'var(--muted2)' }}>weights: {result.dims.map(d => `${d.key} ${Math.round(d.weight * 100)}%`).join(' · ')}</span>}>
            <div style={{ display: 'grid', gap: 8 }}>
              {result.scored.slice(0, 15).map((r, i) => (
                <div key={r.id} style={{ display: 'grid', gridTemplateColumns: mobile ? '20px 1fr 52px' : '24px 16px 220px 1fr 60px 70px', gap: 10, alignItems: 'center' }}>
                  <span style={{ fontFamily: MONO, fontSize: 11, color: i < 3 ? GOLD : 'var(--muted)' }}>{i + 1}</span>
                  {!mobile && <LabLogo org={r.org} size={13} />}
                  <div style={{ minWidth: 0 }}>
                    <div style={{ fontSize: 12.5, fontWeight: 600, color: 'var(--text)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{r.name}</div>
                    <div style={{ fontSize: 10, color: 'var(--muted2)', fontFamily: MONO }}>{Object.entries(r.parts).map(([k, v]) => `${k} ${Math.round(v * 100)}`).join(' · ')}{r.coverage < 1 ? ' · partial' : ''}</div>
                  </div>
                  {!mobile && <div style={{ height: 4, background: 'var(--sep2)' }}><div style={{ height: '100%', width: `${r.score * 100}%`, background: ORG_CONFIG[r.org]?.color ?? 'var(--text)' }} /></div>}
                  <span style={{ fontFamily: MONO, fontSize: 13, fontWeight: 700, color: 'var(--text)', textAlign: 'right' }}>{(r.score * 100).toFixed(0)}</span>
                  {!mobile && <span style={{ textAlign: 'right' }}><AddToBattle item={{ id: r.id, kind: r.kind, name: r.name, org: r.org, board: r.board }} /></span>}
                </div>
              ))}
            </div>
          </Panel>

          <p style={{ fontSize: 11.5, color: 'var(--muted)', marginTop: 12, lineHeight: 1.55 }}>
            How it works: each dimension is normalised to 0–1 across the candidate pool (cost and context on a log scale, lower-is-better metrics inverted), multiplied by its weight and averaged over the dimensions the candidate actually has data for. A missing dimension is skipped — never scored as zero — with a small coverage penalty so a model can't win by omission. Best value = ½ quality + ½ cheapness among candidates at ≥55% of the top quality; budget = cheapest at mid-pack quality or better; fastest = best speed metric at mid-pack quality or better.
          </p>
        </>
      )}
    </PageFrame>
  );
}
